### ISSUE TITLE
Need to update JXcore-Cordova to point to the latest version of JXcore

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/jxcore-cordova#6]
Everything looks good so far but we ran into an issue on building on Mac for Android that will require an update but otherwise should be done between today and tomorrow morning.

**Comment by yaronyg** [comment]
To update there is no change to the repo. We just build a new version that includes the binaries for the version of JXcore we want. So we have figured out how to do that much but we haven't had a chance yet to run the tests.

**Comment by yaronyg** [comment]
Tests on ANdroid and iOS all passed yesterday. Today we'll push update to Azure and test and then we can close.

**Comment by yaronyg** [comment]
We needed to rerun the build (which manually takes 2 hours!) because we didn't upgrade the version numbers. So Enrico wrote 14 different scripts to manage different parts of the process. But some of the existing scripts were a mess that weren't really using the full CPU power, everyone was running on a single CPU. So now we can do a full build in little more than 30 minutes! And nothing manual.

So now the new build needs to be tested locally. Make sure NPM is o.k. with the version number. He'll run the Thali build process and see what blows.

**Comment by enricogior** [comment]
Updated version 0.1.2b available:
https://jxcore.blob.core.windows.net/jxcore-release/jxcore-cordova/0.1.2b/release/io.jxcore.node.jx

**Comment by enricogior** [comment]
Waiting to know if a debug build is required to close the issue.

**Comment by yaronyg** [comment]
For right now I don't think we need the debug build.
